language: objective-c

script:
- xctool -project CFAAction.xcodeproj -scheme CFAAction -sdk macosx ONLY_ACTIVE_ARCH=NO clean build test
- xctool -project CFAAction.xcodeproj -scheme CFAAction-iOS -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO build



