language: objective-c
osx_image: xcode7.3

script:
- set -o pipefail
- xcodebuild test -scheme CFAAction | xcpretty -c
- xcodebuild build -scheme CFAAction-iOS -destination 'platform=iOS Simulator,name=iPad Pro' | xcpretty -c



