language: objective-c

before_install:
- brew update
- brew upgrade xctool

script:
- xctool -project CFAAction.xcodeproj -scheme CFAAction -sdk macosx ONLY_ACTIVE_ARCH=NO clean build test
- xctool -project CFAAction.xcodeproj -scheme CFAAction-iOS -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO build



